{
 "title": "Puptoo",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{service=\"puptoo-processor\"}[24h]))"
    }
   ]
  },
  {
   "title": "Successful Extractions",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(puptoo_successful_extractions_total[24h])) / sum(increase(puptoo_extractions_total[24h]))"
    }
   ]
  },
  {
   "title": "Total Messages Produced per Topic",
   "type": "timeseries",
   "description": "Total messages produced to each topic",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(puptoo_messages_produced_total[$__range])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Total Consumed Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(puptoo_messages_consumed_total[$__range]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Failed Extractions",
   "type": "timeseries",
   "description": "Total Uploads that failed extractions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(puptoo_failed_extractions_total[$__range]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Consumer lag",
   "type": "timeseries",
   "description": "Messages in the announce topic waiting to be picked up by Puptoo. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag{topic=\"platform.upload.announce\", group=\"insights-puptoo\"}) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer lag on partitions",
   "type": "timeseries",
   "description": "Partition view of messages in the announce topic waiting to be picked up by Puptoo ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_consumergroup_group_lag{topic=\"platform.upload.announce\", group=\"insights-puptoo\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer lag on partitions",
   "type": "timeseries",
   "description": "Partition view of messages in the announce topic waiting to be picked up by Puptoo ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_consumergroup_group_lag{topic=\"platform.upload.announce\", group=\"insights-puptoo\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}